#------------------------------------------#
# An example with a muon oscillating in    #
# a homogenous magentic field              #
#------------------------------------------#
#
###########################################
# Run and Output
###########################################
setRunID g2test3
setRecordPeriodicSteps true
setPeriodicStopTime 14.9e-9
setManualTracking true
#
###########################################
# Geometry
###########################################
setUse2D false
setChamberHeight 1.0e10
setChamberRadius 1.0e10
#
###########################################
# Motion
###########################################
setMass 1.88e-28
setTrackFilePath !dynamic
#
#Note setVelProfHistPath with an "!" 
#sets temperature in a Maxwell distribution
#setVelProfHistPath !293
#
setMeanVel 299619080.538
setDefaultPos 0 0 0.01
setDefaultVel 0 0 0
###########################################
# Spin Tracking
###########################################
setTimeLimit 1.49e-04
setGyromagneticRatio -0.00116592091
setEPSRel 1e-07
setEPSAbs 1e-07
setInitialStepSize 1e-9
#
###########################################
# Fields
###########################################
setB0FieldDirection 0 0 1
setB0FieldStrength -29.3*1.4513
setBSextFieldStrength -0.63e-03*29.3
setBSextFieldAxis 0 1 0
setBSextFieldDirection 1 0 0
###########################################
# Run something
###########################################
trackSpins 1