#------------------------------------------#
# An example with a muon oscillating in    #
# a homogenous magentic field              #
#------------------------------------------#
#
###########################################
# Run and Output
###########################################
setRunID g2test5
setRecordPeriodicSteps true
setPeriodicStopTime 5.09e-10
setManualTracking true
#
###########################################
# Geometry
###########################################
setUse2D false
setChamberHeight 1.0e10
setChamberRadius 1.0e10
#
###########################################
# Motion
###########################################
setMass 1.88e-28
setTrackFilePath !dynamic
#
#Note setVelProfHistPath with an "!" 
#sets temperature in a Maxwell distribution
#setVelProfHistPath !293
#
#setMeanVel 299619080.538
setDefaultPos 0 0 0.01665607997099
setDefaultVel 0 0 0
###########################################
# Spin Tracking
###########################################
setTimeLimit 5.08532423208191e-09
setGyromagneticRatio -0.00116592091
setEPSRel 1e-07
setEPSAbs 1e-07
setInitialStepSize 1e-10
#
###########################################
# Fields
###########################################
setB0FieldDirection 0 0 1
setB0FieldStrength -42.52309 #-29.3*1.4513
#setBQuadFieldStrength -0.818378992 #-29.3*0.137*1.4513*0.9994*0.9994/7.11
#setBQuadFieldAxis 0 1 0
#setBQuadFieldDirection 1 0 0
setBSextFieldStrength -0.018459 #-0.63e-03*29.3
setBSextFieldAxis 0 1 0
setBSextFieldDirection 1 0 0
###########################################
# Run something
###########################################
trackSpins 1